# -*- coding: utf-8 -*-
"""Anay Gupta- Copy of Byte Size 1 Python_Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXe6EH9kzuvahgT_e_FdSMg7yqgNNprF

# Printing

Example: Hello World!

This is an example Python program that displays the text “Hello, world!” followed by a description of how many pets someone has.


```
# This is formatted as code
```
"""

# Printing text
print("Hello World!")

# Printing how many pets you have
print("I have 2 dogs.")

"""When you use  `print`,  each new thing that you want to display will be shown on a new line. If you want to display text, you need to write the word `print`, followed by the text in quotes between parentheses: `("insert your text here")`.


Do you notice those lines with `#` signs in front? Those are called **comments**. Comments are really useful to tell people what's happening in your code, as well as a reminder for yourself when you review what you've written. The comments aren't actual code, so you don't need to worry about Python reading them when your programs are running. In other words, they don't get printed out.

## Try it out: Introduce yourself!

Write a program that prints your name and something about yourself. Here’s an example of what your program could display: 
 > `My name is Arya.`
 
 > `I like writing Python programs.`
 
 Please comment each line of your code informatively.
"""

# Prints a sentence with every letter in the English alphabet for people new to typing to try out. 
print("The quick brown fox jumps over the lazy dog.")

"""# Variables

Often, when we're programming, we need to store some pieces of information. A good way to do this is by using **variables**. Variables are like containers: you can put things into them and extract their contents later.

To declare a variable, there are three steps:

1.   Come up with a name for your variable
2.   Write an equals sign (=)
3.   Put the **value** you want to store in your variable after the = sign

## Example: What I ate today

Let's see how we can use a variable to store information about what someone ate for breakfast and lunch today, and then print it.

---
"""

# A variable to store information
meal = "English muffin"
print("Breakfast: " + meal)

# Let's change the variable to something else
meal = "Pizza with ranch dip"
print("Lunch: " + meal)

"""Here, we made a variable called `meal`, and initially assigned it the value of `"English muffin"`. Later on, we reassigned the variable with a different value, `"Pizza with ranch dip"`.  Since we reassigned the variable, `"English muffin"` is completely replaced and we don't have access to that original value any more. If you wanted to keep the original value, you could consider defining a second variable, calling it something like `meal2`.

Do you also notice that `+` sign in the `print` statements? You can use it to chain piece of text together when you want to display more than one word or phrase. This is called **concatenation**.

# Variable types

All of the code above has been used to record and display text information. In Python, text between quotation marks is called a **string**. Referring to examples from before, `"English muffin"` is a string, as is `"I have 2 dogs."`

However, we can store other pieces of information in variables aside from strings. For instance, we can store numbers in variables. There are two primary numeric variable types in Python: **integers** and **floats** (or floating-point numbers). Integers are whole numbers (e.g. 4), and floats are numbers with a decimal part (e.g. 8.26).

Let's see an example of how to define two numeric variables and add them together.
"""

# Define an integer
our_integer = 5

# Define a float
our_float = 3.65

# Add them together, store the result in a variable, and print it out
our_result = our_integer + our_float
print(our_result)

"""Do you notice anything different about how these variables look? With strings, we need to use quotation marks to define them. But with numbers, we can leave out the quotes. That means that `2` and `"2"` are not the same thing: the first is an integer, while the second is a string.

Notice that we can add numeric variables in Python using the `+` operator. So it behaves like traditional addition as well as the concatenation (putting strings together) that you saw earlier. The values of `our_integer` and `our_float` are being combined and stored in `our_result` in the above example.

We have other mathematical operators available to us in Python too:

*   `-` subtraction (e.g. `4 - 2` evaluates to `2`)
*   `*` multiplication (e.g. `3.4 * 10` evaluates to `34`)
*   `/` exact division (e.g. `5/2` evaluates to `2.5`)
*  `//` integer division (leaving off the decimal part, e.g. `5//2` evaluates to `2`)

## Example: Currency Converter 



This example demonstrates how to create and update integer and float variables. The following program converts any amount (in dollars) to rupees, and displays the result. The amount is stored in a variable `amt_in_dollars`, and the conversion rate is stored in a variable, `conversion_rate`. The converted amount is stored in `amt_in_rupees` and displayed.
"""

currency_rate = 90
amt_in_pounds= 100
amt_in_rupees= amt_in_pounds*currency_rate
print(amt_in_rupees)

"""When we printed this time, we couldn't use the `+` operator directly between `"$"` and `amt_in_dollars`. That's because `"$"` is a string, but `amt_in_dollars` is an integer. So we had to convert the `amt_in_dollars` to a string, by using `str()` surrounding that variable.

Do you notice that there are loads of decimal places after the decimal point in the final Rs. amount? Decimal mathematics isn't quite exact in Python, but you can see the result is pretty close.

## Try it out: Judge for the Olympics 

Write an Olympic Judging program that outputs the average scores from 3 different judges. Write a program with three variables for each score, called `score_a`, `score_b` and `score_C`  respectively. Set the scores (out of 10) to integers of your choice, and print them one after the other. Then, calculate the average of the three scores, and print the result.

Your output should appear like this: 

```
Judge 1: 10
Judge 2: 9
Judge 3: 8
Average Score: 9
```

This example combines several concepts from previous exercises and examples. If you're unsure about how to start, break down the problem into parts that are similar to the things we've just covered.

*Hint: calculate the **total** first (and store this in a variable) before you calculate and print your average.*
"""

# Write your Olympic Judging program here:
score_a = 0
score_b = 10
score_C = 7
total = score_a + score_b + score_C
avg = total/3
int_avg = int(avg)
print ("Judge 1:", score_a)
print ("Judge 2:", score_b)
print ("Judge 3:", score_C)
print ("Average Score:", avg)
print ("Average In Integer:", int_avg)

"""# User Input

When we run Python programs, we aren't restricted to specifying all the strings, integers and floats ourselves. We can also request input from users of your program. This is a powerful tool to make your programs flexible and personalised. AI applications frequently make use of user input to tailor an experience appropriately to a particular person.

## Example: A better Currency Converter

Let's suppose that you just got back from a holiday to the US. You still have some dollar bills remaining, and you want to convert these dollars back to Rs. This program will respond to your requests and convert your money back for you. Give it a run!
"""

# Retrieve user's name and store in variable
name = input("Hey there! What's your name? ")

# Retrieve amount to be converted from the user
amt_in_dollars = int(input(name + ", what dollar amount are you looking to convert? "))

conversion_rate = 69.18

# Convert dollars to rupees using conversion_rate
amt_in_rupees = amt_in_dollars * conversion_rate

# Print the converted amount

print("Sweet! $" + str(amt_in_dollars) + " is Rs. " + str(amt_in_rupees))

"""Isn't that neat? This code has read in your name, addressed you personally asking for how much money you want to convert, and performed the conversion for you.

To get user input, we perform the following steps:


1.   Come up with a variable name to store your input
2.   Write `=`
3.   Write `input()`
4.   Within the parentheses, write the message that prompts the user to enter something

By default, user input gets read in as a string. In the above example, we wanted to retrieve the dollar amount to convert from the user, but we don't want to store that as a string since we want to use it in calculations. So we need to convert it to an integer. We do this by enclosing that expression in `int()`: 

`amt_in_dollars = int(input(name + ", what dollar amount are you looking to convert? "))`

## Try it out: A better way to Judge the Olympics

Instead of setting the scores yourself, extend the Olympics judging program so that it asks for input from each judge, and then calculates the average of the three scores. The output should look like this:

```
Judge 1, what’s your score? 10
Judge 2, what’s your score? 9
Judge 3, what’s your score? 8
Average score: 9
```

This time, instead of storing the total in a separate variable from the average, try to jump to the average in just one step. Note that you can use parentheses to specify that you want an expression to be calculated before something else, like this:

```
ans = (6 + 2 + 5) / 13
```
This way, the sum `6 + 2 + 5` gets calculated first, giving `13`. Then `13` is divided by `13` to give the answer, which is `1`. This value is stored in `ans`.
"""

# Write your Extended Olympic Judging program here: 

score_a = float(input("Judge 1, what's your score? "))
score_b = float(input("Judge 2, what's your score? "))
score_C = float(input("Judge 3, what's your score? "))
avg = (score_a + score_b + score_C)/3
int_avg = round(avg)
print ("Average Score:", avg)
print ("Average Rounded To Nearest Integer:", int_avg)

"""# Conditionals

In all the programs above, we have a fixed order in which things will happen. For instance, with our judge scores above, we know that we will be taking in input from 3 judges, calculating the average and printing it out.

However, we might want to specify some alternative ways in which a program could run. In plain English, this means something like:

"if something is the case, execute the program in one particular way; otherwise do it another way"

We can achieve this in Python by using **Boolean** variables. A Boolean is another type of variable that can take on just two values: `True` and `False`.

## Example: Self-Driving Car at a Traffic Light
"""



"""We're sitting in a nice Tesla that is approaching a traffic light. The Tesla is looking out to see whether the green light is illuminated."""

# We define a new Boolean variable called green_light 
# In this case, the green light is illuminated, so we set the variable to True
green_light = True

if green_light: 
  print("Good to go!")
else: 
  print("Don't go yet...")

"""Nice, our Tesla can sail through the green light with no problems. But now we're approaching another traffic light that is not green:"""

# In this case, we're approaching a red light, so we set the variable to False
green_light = False

if green_light: 
  print("Good to go!")
else: 
  print("Don't go yet...")

"""Notice above that each `print()` statement above is indented and preceded by one of two lines:

```
if green_light:
```
or
```
else:
...
```

When you write `if`, Python checks to see whether the variable or expression after it evaluates to `True`. If it does, then the indented code after it will execute, and Python will skip the indented code after the `else`. If it evaluates to `False`, then the indented code after the `if` statement is skipped, and the indented code after `else` will execute. The examples above show both of these in action.

Note that when using `if` and `else` statements, you need to end each of these lines with a colon (`:` ) and indent the subsequent code with a tab.

## Comparison operators: `==, !=, >, <, >=, <=`

So far, we've been setting variables directly to Boolean values. Sometimes, however, we want to compare other values or expressions to each other. To do this, we can use **comparison operators**. 

There are six main types of comparison operator:


1.   `==` checks to see if two values/expressions are equal
2.   `!=` checks to see if two values/expressions are not equal
3.   `>` checks to see if the left-hand value/expression is greater than the right-hand value/expression
4.   `<` checks to see if the left-hand value/expression is less than the right-hand value/expression
5. `>=` checks to see if the left-hand value/expression is greater than or equal to the right-hand value/expression
6. `<=` checks to see if the left-hand value/expression is less than or equal to the right-hand value/expression

If the comparison condition is satistfied, the whole expression will evaluate to `True`. If it's not, the whole expression evaluates to `False`.

Let's take a look at some simple examples of this. Run the following cell and examine the outputs:
"""

# Define a variable called test
test = 2

# Let's see if test is equal to 2, and print out the result
result = test == 2
print(result)

# Let's see if test is greater than or equal to 4, and print out the result.
# This time, we're going to do it all in one line
print(test >= 4)

# Finally, let's see if the result of 3 - test is not equal to the result of test/2.
print(3 - test != test/2)

"""Comparison operators also work on strings, as you can see below if you run the cell. This program combines the comparison operators with an `if` statement to get some different outputs. Will anything be printed out in this case?"""

# Define a test string
test_string = "hello"

# Will anything be printed here?
if test_string == "pink":
  print("The test string is pink")

"""Here, since we didn't specify an alternative output to print out, nothing gets printed. It's fine not to have an `else` statement if you don't want it!

## Now you try!

**Write** two expressions of your own, with the first one evaluating to `True` and the second one evaluating to `False`. Print out the values of your expressions as you go.
"""

# Write your first expression here
true = (5 != 4)
print(true)

# Write your second expression here

false = (5 == 21)
print(false)

"""## Controlling the traffic lights

Remember the self-driving car example from before? It was pretty good, but we want to make it better. There, we only specified whether or not a light was green, but there are actually two alternatives for when a light is not green: it could be red or yellow.

This time, we're going to let a user input what colour they want the traffic light to be. Then we'll tell the Tesla what it needs to do depending on the colour of the light that was entered.
"""

# Get user input about the traffic light colour
light = input("What colour is the traffic light? ")

# Don't worry about this line; it's just formatting the string so that there's
# no extra whitespace at the ends and it's all in lower case
light = light.lower().strip()

# Tell the car what it needs to do based on the colour of the light
if light == "red": 
  print("Don't go yet... ")
elif light == "yellow":
  print("Get ready to go... ")
elif light == "green":
  print("Good to go!")
else:
  print("Huh?")

"""This example is a little more involved than before. There are two main things to notice here:


1.   The above program uses the word `elif`. This is useful if you have multiple conditions you want to check. `if`/`else` on their own is fine if there's just one condition you want to check, but here we're seeing if the light is red, yellow or green.
2.   The final `else` statement might seem unnecessary, but we've included it in case the user enters something other than red, yellow or green. If a Tesla saw a purple light, it might be confused!

## Logical operators: `and`, `or`, `not`

In the above examples, we were only checking one expression at a time. But sometimes we want to check more than one at once, or negate some expression that we've already checked. There are three keywords in Python for this:


1. `and` checks if both the left-hand and right-hand expressions are `True`. If they are, the whole expression evaluates to `True`; otherwise it evaluates to `False`.

2. `or` checks if either the left-hand or right-hand expressions are `True` (or both of them). If at least one of these expressions evaluates to `True`, then the whole expression evaluates to `True`; otherwise it evaluates to `False`.

3. `not` will reverse the value of whatever expression we are checking. So `not True` is the same as `False`, and `not False` is the same as `True`.

Run the cell below to see the results of each of the expressions within.
"""

# Define some Booleans
bool_a = 2 * 3 == 6 # this evaluates to True
bool_b = 9 - 4 != 5 # this evaluates to False

# Expression 1
print(bool_a and bool_b)

# Expression 2
print(bool_a or bool_b)

# Expression 3
print(not bool_b)

"""# Loops

To motivate the need for while loops, let's re-visit the if-condition. Recall that an `if` statement allows you to do something UNLESS a condition is `False`. If the condition is `False`, nothing is executed. What if we want to do something UNTIL a condition becomes `False`?  This is exactly what loops are for: to execute a particular task repeatedly until some condition no longer holds `True`.

## While loops: A personalized Self-Driving Car

Let's explore this with an example. Let’s go back to our self-driving Tesla, but this time, let's personalize it. Suppose that our Tesla (let's call it *Jarvis*), only starts when the user summons it with a command, say "*Jarvis, energize!*". If we don’t enter that command, the car doesn’t start. We know this can be programmed with a simple `if` condition, like so:
"""

# Define the predetermined summon in a variable
summon = "Jarvis, energize!"

# Ask the user for the command
command = input("What’s your command? ")

# Tell the car what to do based on the correctness of the command
if command == summon:
  print("Your wish is my command!")
else: 
  print("Sorry, I don’t understand.")

"""… Now, instead of just giving the user a single try, what if we want to let the user keep guessing until they guess correctly?

We can do that with something called a `while` loop. Take a look at this program, and give it a whirl:
"""

# Define the predetermined summon in a variable
summon = "Jarvis, energize!"

# Ask the user for the command
command = input("What’s your command? ")

# While the command isn't the summon we're looking for... then execute the indented block
while command != summon: 
  print("Sorry, I don't understand.") 
  command = input("What's your command? ")
  
# This line of code will only execute when the loop is finished, i.e., when command is the predetermined summon
# Note how this line is NOT indented like the statements inside the while-loop
print("Your wish is my command!")

"""In simple English, the `while` loop can be translated as: "Until `command` is not the same as `summon`, ask user for input."

Here's what a `while` loop looks like: 
```
while condition
  ... do something ... 
 ```
It looks a lot like an `if` statement. The only difference is the word "while" in place of the word "if". The condition still has to be something that evaluates to a boolean. The code under the `while` loop is the body. If the condition is `True`, it executes. 

EVERY TIME it executes, the condition is checked again. Unless the condition has become `False`, the body runs again.

## Try it out:  Free tickets for the IPL 

You just landed 20 tickets for the IPL finals and generously want to give it away. With your recently acquired programming chops, you decide to write a program that keeps track of the tickets you have left. While there are still tickets left with you, ask the user how many tickets they would like to buy. Then print out how many are left with you after the purchase.
 
Bonus points if your program can catch the case where your user tries to buy more tickets than you have left with you. In that case, you should print a message to the yser saying that their request isn’t possible. 

Here's an example of what one run of the program might appear like: 

```
I'm giving away free tickets for the IPL. 

How many do you need? 5 
Great! I have 15 tickets left. 

How many do you need? 17
Sorry, I don't have that many. 

How many tickets do you need? 15
Great! I have 0 tickets left. 

All sold out!
```

###Hit the dropdown and run the code to see a hint

Hints:
* You can set a `while` loop header condition to *anything* that evaluates to a Boolean. In this case, we want to make sure that there are still tickets left. This means that we'll want to compare the ticket count to something. What will this comparison look like?
* Suppose that you store the number of tickets that someone requests in a variable called `tickets`. Then after that value is stored, you can subtract it from `tickets_left` to figure out the new number of remaining tickets. This updated value will then get checked again in the next run of the while loop.

### Enter your code below
"""

# Complete the IPL ticket-giveaway program. 
need = 0
left = 20
print("I'm giving away some free tickets for the upcoming IPL and I have 20 in total")
while left > 0:
  need = int(input("How many do you need? "))
  left = left - need
  if left<0 or left>20:
    print("Sorry, invalid request.")
    left = left + need
  else:
    print("Sure, I have", left, "ticket(s) left.")
print("Sold out! Thanks for stopping by :)")

"""## For loops

A while loop works well when we don't know in advance how many times we will have to do something. But what if we know exactly how many times you'll have to do something?

We can use a `for` loop! Here's an example of what it looks like.
"""

for i in range(4): 
  # Do this 4 times
  print("This is iteration number: " + str(i))

"""A `for` loop consists of three main things: 
*   You say "`for i in range`"
*  An integer in parentheses, which is the number of times you want to do something
*  The indented code, called body, which will execute repeatedly

## Example: A more secure Self-Driving Car 

Our friend at Tesla, Elon Musk, just told us it isn’t safe to let the user have unlimited go’s at guessing the command. He recommends we give the user only five tries to guess the command. Let’s see how we might use our handy-dandy `for` loop here:
"""

# Define the predetermined summon in a variable
summon = "Jarvis, energize!"

# Try the command five times
for i in range(5): 
  command = input("What’s your command? ")
  if command == summon:
     print("Your wish is my command!")
     break
  else: 
     print("Sorry, I don’t understand!")

"""Notice a new `break` statement in the `if` condition? When the condition is `True`, the break statement skips the entire loop even before it finishes all its iterations. In the above program, it ensures that the user is not asked to give the command again if they've gotten it right before the first five tries.

## Try it out: Judging for the Olympics v3 

Remember the Olympics Judging program from earlier? Re-write it with a for-loop. As a reminder, the program asks a score from each of the three judges, and then calculates the average. The output looks like this: 

```
Judge 1, what’s your score? 10
Judge 2, what’s your score? 9
Judge 3, what’s your score? 8
The average score is 9. 

```
"""

# Write your new version of the Olympics Judging program with for loops here.
totalscore = 0
for i in range(3):
  score = float(input(("Judge " + str(i+1)) + ", what's your score? "))
  totalscore = totalscore + score
avg = totalscore/3
avg_int = round(avg)
print("The exact average score is", avg)
print("The average score rounded to the nearest integer is", avg_int)

"""# Lists



Another common data type is lists.  You can think of lists as storing multiple variables, or a collection of variables, in one place.  It's also important to note that the variables are in a particular order and are each assigned an index in the list.
"""

# Let's create a grocery list for when we go to the store
groceries = []
groceries.append('apples')
groceries.append('milk')
groceries.append('bread')
groceries.append('cheese')


for var, item in enumerate(groceries):
  print(item + ' is at index: ' + str(var))

"""## Try it out: Best Foot Forward
You’re applying to Stanford and you realize you want to submit only the best score from all your attempts at the SAT. The scores from all the attempts is stored in a list, called `scores`. Write a program that traverses the list and then prints the highest score from the list. 

**Note**: Do not use the built-in function `max` in your program!
"""

# Complete this program to find and print the highest score from the list
scores = [1600, 1590, 1550]
high = -100000000
for i in range(3):
  if scores[i] > high:
    high = scores[i]
print("The highest score is", high)

"""# Functions



A Python function is similar to how we think of functions in math. You've actually already made use of functions earlier-- `range`, `input` and `append` are all examples of functions. You can think of these as pre-defined functions in Python that can be called for various uses. Now, you'll learn how to make your own functions.

Let's say you're building a chatbot, Jarvis, which needs to greet the user every time it's summoned, like so:
"""

print("Hi!")
print("Allow me to introduce myself. I'm Jarvis, and I can call and mesage people for you. I can also share a joke or two.")
print("What can I help you with?")

"""Every time a user summons Jarvis, we call these three lines of code. Even if Jarvis is summoned 3-4 times, that's a lot of lines of code required. Instead, we can assign these lines of code to a `function`. We'll call the function `greeting`, and define it in the following way. 

Every function you define contains the word `def`, the name of your function, a pair of parenthses, and a colon, followed by some code underneath. When we define a function, nothing actually happens in the console. Try this:
"""

def greeting(message): 
  return message

"""At this point, we have merely taught Jarvis how to print a greeting. Now we have to tell Jarvis to actually do it, and we do this by calling the function, like so:"""

greeting()

"""Each time we call it, the code in the function gets executed. This is part of why functions are valuable. They allow us to save some code for later, and then use and re-use it without typing it out each time.

## Variable Scope in Functions

For the purpose exploring functions further, let's use a shorter greeting and add the user's name to it. Then we can declare a variable with the name, like we normally would:
"""

def greeting(): 
  name = "Arya"
  print("Hi " + name + "!)
  
greeting()

"""But watch out, if you do this, the variable `name` is only available within the function. If you try to use `name` outside the function, it causes an error. Do you see an error when you run this program?"""

def greeting(): 
  name = "Arya"
  print("Hi " + name + "!")  
  
greeting()
print(name)

"""But here's where Python gets a little funky. If you declare the variable OUTSIDE a function, you can still access it INSIDE the function. Take a look at this:"""

name = "Arya"

def greeting(): 
  print("Hi " + name + "!")
  
greeting()
print(name)

"""Here's another place where Python gets REALLY funky. If a variable is declared outside a function, and you try to CHANGE it inside the function, you actually create ANOTHER variable of the same name! In this example, there are two variables called `name`. One of them lives inside `greeting`, and the other lives outside of it. Run this code and see what happens."""

name = "Arya"

def greeting():
  name = "Alex"
  print("Hi " + name + "!")
  
greeting()  # This print statement will refer to the version of name inside greeting()
print(name) # This print statement will refer to the version of name on the first line

"""## Functions with Parameters


As it stands now, functions are pretty limited; they always do the same thing. The function `greeting` always greets Arya.

We can make a function behave differently by re-assigning the variable `name` each time, but that would be annoying. Fortunately, there's a better way to do this, and it exists in the form of **parameters**, which are pieces of information you can give the function when you call them. 

A parameter is basically a variable name. You put the variable name in the function's parentheses, and you can then use the name in the function as though it were a variable you declared.
"""

def greeting(name): 
  print("Hi " + name + "!")

"""But where does this variable get its value from?

You actually give the variable a value when you call the function, like the following lines of code. Give it a whirl, what do you get?
"""

greeting("Arya")
greeting("Alex")
greeting("Adi")

"""Functions can also have **multiple** parameters. Let's say we want to print the current temperature with the greeting. Then the provide the paramters in paretheses, separated by commas."""

# Function definition includes two parameters for name and temp
def greeting(name, temp): 
  print("Hi " + name + "!")
  print("It's " + str(temp) + " degree celsius today.")

# While calling the function, we provide the values for BOTH parameters
greeting("Arya", 21)
greeting("Alex", 37)

"""## Functions with Return Values

When you write a function, you have the option of making it return a value. Here's an example of a function that returns a `string variable` with a greeting. 

Run the program. Notice how the first print statement is empty, and the second print statement prints the string returned by the `greeting` function.
"""

# Defining a function that returns a greeting string 
def greeting(name): 
  return "Hey " + name + "!"

# Here, a variable is declared and printed
my_greeting = ""
print(my_greeting)

# Here, the variables is assigned to the value returned by the greeting function
my_greeting = greeting("Arya")
print(my_greeting)

"""## Try it out: Can you predict what Dory sings?

*Finding Dory* is an amazing film! Dory, the friendly but forgetful blue tang fish, often sings a song to herself and her friends to keep motivation high when they are feeling lost. The following program prints out what Dory sings. **Without running the program, can you predict its output?** 

*I think the output will be*

I sing for Nemo : Just keep swimming. Just keep swimming. Just keep swimming.

I sing for Marlin : Just keep swimming. Just keep swimming. Just keep swimming.

I sing for Destiny : Just keep swimming. Just keep swimming. Just keep swimming.
"""

def sing_song(friend, quote):
  song = "I sing for " + friend + ": "
  for i in range(3): 
    song = song + quote
  return song

def sing_for_all(quote): 
  friends = ["Nemo", "Marlin", "Destiny"]
  song = ""
  for friend in friends: 
    print(song + sing_song(friend, quote))
    
sing_for_all("Just keep swimming. ")

"""Now run the program and compare your solution to the output. How did you do? :)

## Try it out: Turn up the temperature

You're probably used to reading the temperature in Celsius units. Unfortunately, your soon-to-be friends from Stanford don't understand Celsius; they are only used to Farenheit. To make any discussion about weather easier with them, write a program that helps you convert the temperature between the Celsius and Farenheit: 

1.   Write a function called `c_to_f` that takes an input `c_temp`, a temperature in Celsius, and converts it to `f_temp`, that temperature in Fahrenheit. It should then return `f_temp`. The equation you should use is: 

> > > >  $F = (1.8 * C) + 32$


2.   Let’s test your function with a value of 0 Celsius. Print out your output.
"""

# Define your function here

def c_to_f(c_temp):
  f_temp = (1.8 * c_temp)+32
  return f_temp

# Call your function and print output here

farenheit = c_to_f(int(input("Hello my future self, I hope this program helps you socialise with those imperial unit-loving stanford people. Please enter a temperature in degrees celsius ")))
print("The temperature in farenheit is", farenheit)
if farenheit < 68:
  print("Brrrr.... That's cold!")



"""# CONGRATULATIONS!
Well done for finishing this notebook!
"""

print("yay!")